services:
  app:
    build:
      context: .
    container_name: app
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    command: sh -c "composer install --optimize-autoloader --no-dev && php artisan migrate && php-fpm"
    volumes:
      - ./:/var/www
      - ./php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
